### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by michaelsauter**
* Make it work without Jira
* Disable versioned dev envs by default
* Display fixes

### CODE REVIEW

**Comment by michaelsauter** [comment]
@metmajer 8059204 adds a way to configure a different Jira project. You'd just ned to use `project.jiraProjectKey` instead of `project.key` where applicable.

**Comment by michaelsauter** [comment]
The test failure is due to `ProjectSpec.groovy:507`. That expects calls to load Jira things - now that we have made those conditional (only executed when `jiraUseCase.jira` is present), the expectancy fails. I am not sure how to best fix this - removing the expected calls makes the tests pass, but it is probably not what the author of the test wanted :)

**Comment by metmajer** [comment]
@michaelsauter I'll have a look into the tests and fill in the invocation of getProjectKey() into the callers of the JiraService.foo(String projectKey) methods.

**Comment by metmajer** [comment]
Reolved by #127

**Pull request closed without merging**
