### PR TITLE
Create documents only if documentType is applicable in the current context

### PR DESCRIPTION
**Pull request by metmajer**

### CODE REVIEW

**Comment by metmajer** [comment]
Fixes #1.

**Comment by metmajer** [comment]
Needs squashing before merge.

**Comment by metmajer** [comment]
Set to WIP since I want to assert that we fail if a document is applicable but cannot be created.

**Comment by metmajer** [comment]
@clemensutschig ready for review

**Review by clemensutschig — APPROVED** [review]
very nice @metmajer

**Pull request merged**
