### PR TITLE
Support doc generation scheduling

### LINKED ISSUE #28: Support doc generation scheduling by GAMP category, etc.
We want to be able to efficiently schedule documents to be generated in a generic fashion. In terms of LeVA documents, scheduling shall be based on the following criteria:

- The project's GAMP category (requires a new `levaDocs` capability in `metadata.yml`)
- Pipeline phase (build, deploy, test, etc.) and phase lifecycle stage (post-start, pre-end, etc.)
- Repository type (`ods`, `ods-service`, `ods-test`)

The implementation shall simplify the creation of arbitrary documents and LeVA documents in particular. The to-be-implemented LeVA documents scheduler shall decide which concrete documents need to be created (and which not), based on the above criteria.

### PR DESCRIPTION
**Pull request by metmajer**
Closes #28.

### CODE REVIEW

**Comment by metmajer** [comment]
@clemensutschig like big numbers? :)

```
$ ./gradlew clean test
...
<===========--> 90% EXECUTING [11s]
> :test > 7504 tests completed
```

**Comment by metmajer** [comment]
The new architecture deserves some explanation and looks as follows:

### DocGenService

The _DocGenService_ simply abstracts the DocGen service's REST API, providing a low-level, generic `createDocument` functionality for PDF generation.

### DocGenUseCase

The _DocGenUseCase_ builds upon the _DocGenService_ implementation, providing higher-level, generic functionality, such as `createDocument` and `createOverallDocument`. Here, higher-level means that, next to creating the actual document, an archive is created containing the resulting PDF document and the raw data it's based on. Also, the archive is appended to the pipeline and Nexus as pipeline artifacts.

### LeVADocumentsUseCase

Extends _DocGenUseCase_ and provides implementations for all currently supported LeVA compliance documents (and overall documents). Further, it exposes the `supported documents` in a data structure, so an outside scheduler can invoke the document generator method for each of them.

### DocGenScheduler

Provides a `run` method that is parameterized with the scheduling criteria described in #28, and determines, based on the scheduling criteria, which documents are to be created.

### LeVADocGenScheduler

Provides a concrete scheduler implementation for LeVA documents, based on pre-defined scheduling criteria.

**Comment by metmajer** [comment]
This architecture brings us closest to extracting the LeVA document generation into a dedicated plugin soon. Additionally, the number of tests has been increased drastically. We now efficiently test every combination of scheduling criteria for each LeVA document type. Because of generally better abstraction, we were able to improve the depth of interaction-based testing for each document type, too.

**Comment by metmajer** [comment]
@clemensutschig ready for review

**Comment by metmajer** [comment]
Here are tables showing the documents to be generated per GAMP Category / Phase / Stage, etc. Those tables are an almost exact representation of our test definitions in https://github.com/opendevstack/ods-mro-jenkins-shared-library/blob/custom/leva-docs-refactoring/test/org/ods/scheduler/LeVADocumentSchedulerSpec.groovy.

#### GAMP 1

```
| documentType             | project        | repo             | phase                   | stage                                         || result
|--------------------------|----------------|------------------|-------------------------|-----------------------------------------------||------–
| DocumentType.DSD         | PROJECT_GAMP_1 | null             | PipelinePhases.INIT     | PipelinePhaseLifecycleStage.PRE_END           || true
| DocumentType.FS          | PROJECT_GAMP_1 | null             | PipelinePhases.INIT     | PipelinePhaseLifecycleStage.PRE_END           || true
| DocumentType.FTP         | PROJECT_GAMP_1 | null             | PipelinePhases.TEST     | PipelinePhaseLifecycleStage.POST_START        || true
| DocumentType.IVP         | PROJECT_GAMP_1 | null             | PipelinePhases.TEST     | PipelinePhaseLifecycleStage.POST_START        || true
| DocumentType.TIP         | PROJECT_GAMP_1 | null             | PipelinePhases.DEPLOY   | PipelinePhaseLifecycleStage.POST_START        || true
| DocumentType.OVERALL_TIR | PROJECT_GAMP_1 | null             | PipelinePhases.FINALIZE | PipelinePhaseLifecycleStage.PRE_END           || true
| DocumentType.FTR         | PROJECT_GAMP_1 | REPO_ODS_CODE    | PipelinePhases.TEST     | PipelinePhaseLifecycleStage.POST_EXECUTE_REPO || true
| DocumentType.IVR         | PROJECT_GAMP_1 | REPO_ODS_CODE    | PipelinePhases.TEST     | PipelinePhaseLifecycleStage.POST_EXECUTE_REPO || true
| DocumentType.IVR         | PROJECT_GAMP_1 | REPO_ODS_SERVICE | PipelinePhases.TEST     | PipelinePhaseLifecycleStage.POST_EXECUTE_REPO || true
| DocumentType.TIR         | PROJECT_GAMP_1 | REPO_ODS_CODE    | PipelinePhases.DEPLOY   | PipelinePhaseLifecycleStage.POST_EXECUTE_REPO || true
| DocumentType.TIR         | PROJECT_GAMP_1 | REPO_ODS_SERVICE | PipelinePhases.DEPLOY   | PipelinePhaseLifecycleStage.POST_EXECUTE_REPO || true
```

#### GAMP 3

```
| documentType             | project        | repo             | phase                   | stage                                         || result
|--------------------------|----------------|------------------|-------------------------|-----------------------------------------------||------–
| DocumentType.DSD         | PROJECT_GAMP_3 | null             | PipelinePhases.INIT     | PipelinePhaseLifecycleStage.PRE_END           || true
| DocumentType.IVP         | PROJECT_GAMP_3 | null             | PipelinePhases.TEST     | PipelinePhaseLifecycleStage.POST_START        || true
| DocumentType.TIP         | PROJECT_GAMP_3 | null             | PipelinePhases.DEPLOY   | PipelinePhaseLifecycleStage.POST_START        || true
| DocumentType.URS         | PROJECT_GAMP_3 | null             | PipelinePhases.INIT     | PipelinePhaseLifecycleStage.PRE_END           || true
| DocumentType.OVERALL_TIR | PROJECT_GAMP_3 | null             | PipelinePhases.FINALIZE | PipelinePhaseLifecycleStage.PRE_END           || true
| DocumentType.IVR         | PROJECT_GAMP_3 | REPO_ODS_CODE    | PipelinePhases.TEST     | PipelinePhaseLifecycleStage.POST_EXECUTE_REPO || true
| DocumentType.IVR         | PROJECT_GAMP_3 | REPO_ODS_SERVICE | PipelinePhases.TEST     | PipelinePhaseLifecycleStage.POST_EXECUTE_REPO || true
| DocumentType.TIR         | PROJECT_GAMP_3 | REPO_ODS_CODE    | PipelinePhases.DEPLOY   | PipelinePhaseLifecycleStage.POST_EXECUTE_REPO || true
| DocumentType.TIR         | PROJECT_GAMP_3 | REPO_ODS_SERVICE | PipelinePhases.DEPLOY   | PipelinePhaseLifecycleStage.POST_EXECUTE_REPO || true
```

#### GAMP 4

```
| documentType             | project        | repo             | phase                   | stage                                         || result
|--------------------------|----------------|------------------|-------------------------|-----------------------------------------------||------–
| DocumentType.CS          | PROJECT_GAMP_4 | null             | PipelinePhases.INIT     | PipelinePhaseLifecycleStage.PRE_END           || true
| DocumentType.DSD         | PROJECT_GAMP_4 | null             | PipelinePhases.INIT     | PipelinePhaseLifecycleStage.PRE_END           || true
| DocumentType.FTP         | PROJECT_GAMP_4 | null             | PipelinePhases.TEST     | PipelinePhaseLifecycleStage.POST_START        || true
| DocumentType.TIP         | PROJECT_GAMP_4 | null             | PipelinePhases.DEPLOY   | PipelinePhaseLifecycleStage.POST_START        || true
| DocumentType.URS         | PROJECT_GAMP_4 | null             | PipelinePhases.INIT     | PipelinePhaseLifecycleStage.PRE_END           || true
| DocumentType.OVERALL_TIR | PROJECT_GAMP_4 | null             | PipelinePhases.FINALIZE | PipelinePhaseLifecycleStage.PRE_END           || true
| DocumentType.IVP         | PROJECT_GAMP_4 | null             | PipelinePhases.TEST     | PipelinePhaseLifecycleStage.POST_START        || true
| DocumentType.TIR         | PROJECT_GAMP_4 | REPO_ODS_CODE    | PipelinePhases.DEPLOY   | PipelinePhaseLifecycleStage.POST_EXECUTE_REPO || true
| DocumentType.TIR         | PROJECT_GAMP_4 | REPO_ODS_SERVICE | PipelinePhases.DEPLOY   | PipelinePhaseLifecycleStage.POST_EXECUTE_REPO || true
| DocumentType.FTR         | PROJECT_GAMP_4 | REPO_ODS_CODE    | PipelinePhases.TEST     | PipelinePhaseLifecycleStage.POST_EXECUTE_REPO || true
| DocumentType.IVR         | PROJECT_GAMP_4 | REPO_ODS_CODE    | PipelinePhases.TEST     | PipelinePhaseLifecycleStage.POST_EXECUTE_REPO || true
| DocumentType.IVR         | PROJECT_GAMP_4 | REPO_ODS_SERVICE | PipelinePhases.TEST     | PipelinePhaseLifecycleStage.POST_EXECUTE_REPO || true
```

#### GAMP 5

```
| documentType             | project        | repo             | phase                   | stage                                         || result
|--------------------------|----------------|------------------|-------------------------|-----------------------------------------------||------–
| DocumentType.CS          | PROJECT_GAMP_5 | null             | PipelinePhases.INIT     | PipelinePhaseLifecycleStage.PRE_END           || true
| DocumentType.DSD         | PROJECT_GAMP_5 | null             | PipelinePhases.INIT     | PipelinePhaseLifecycleStage.PRE_END           || true
| DocumentType.DTP         | PROJECT_GAMP_5 | null             | PipelinePhases.BUILD    | PipelinePhaseLifecycleStage.POST_START        || true
| DocumentType.FS          | PROJECT_GAMP_5 | null             | PipelinePhases.INIT     | PipelinePhaseLifecycleStage.PRE_END           || true
| DocumentType.FTP         | PROJECT_GAMP_5 | null             | PipelinePhases.TEST     | PipelinePhaseLifecycleStage.POST_START        || true
| DocumentType.IVP         | PROJECT_GAMP_5 | null             | PipelinePhases.TEST     | PipelinePhaseLifecycleStage.POST_START        || true
| DocumentType.SCP         | PROJECT_GAMP_5 | null             | PipelinePhases.BUILD    | PipelinePhaseLifecycleStage.POST_START        || true
| DocumentType.TIP         | PROJECT_GAMP_5 | null             | PipelinePhases.DEPLOY   | PipelinePhaseLifecycleStage.POST_START        || true
| DocumentType.URS         | PROJECT_GAMP_5 | null             | PipelinePhases.INIT     | PipelinePhaseLifecycleStage.PRE_END           || true
| DocumentType.OVERALL_DTR | PROJECT_GAMP_5 | null             | PipelinePhases.BUILD    | PipelinePhaseLifecycleStage.PRE_END           || true
| DocumentType.OVERALL_SCR | PROJECT_GAMP_5 | null             | PipelinePhases.TEST     | PipelinePhaseLifecycleStage.PRE_END           || true
| DocumentType.OVERALL_SDS | PROJECT_GAMP_5 | null             | PipelinePhases.BUILD    | PipelinePhaseLifecycleStage.PRE_END           || true
| DocumentType.OVERALL_TIR | PROJECT_GAMP_5 | null             | PipelinePhases.FINALIZE | PipelinePhaseLifecycleStage.PRE_END           || true
| DocumentType.DTR         | PROJECT_GAMP_5 | REPO_ODS_CODE    | PipelinePhases.BUILD    | PipelinePhaseLifecycleStage.POST_EXECUTE_REPO || true
| DocumentType.FTR         | PROJECT_GAMP_5 | REPO_ODS_CODE    | PipelinePhases.TEST     | PipelinePhaseLifecycleStage.POST_EXECUTE_REPO || true
| DocumentType.IVR         | PROJECT_GAMP_5 | REPO_ODS_CODE    | PipelinePhases.TEST     | PipelinePhaseLifecycleStage.POST_EXECUTE_REPO || true
| DocumentType.IVR         | PROJECT_GAMP_5 | REPO_ODS_SERVICE | PipelinePhases.TEST     | PipelinePhaseLifecycleStage.POST_EXECUTE_REPO || true
| DocumentType.SCR         | PROJECT_GAMP_5 | REPO_ODS_CODE    | PipelinePhases.BUILD    | PipelinePhaseLifecycleStage.POST_EXECUTE_REPO || true
| DocumentType.SCR         | PROJECT_GAMP_5 | REPO_ODS_TEST    | PipelinePhases.TEST     | PipelinePhaseLifecycleStage.POST_EXECUTE_REPO  || true
| DocumentType.SDS         | PROJECT_GAMP_5 | REPO_ODS_CODE    | PipelinePhases.BUILD    | PipelinePhaseLifecycleStage.PRE_EXECUTE_REPO  || true
| DocumentType.SDS         | PROJECT_GAMP_5 | REPO_ODS_TEST    | PipelinePhases.BUILD    | PipelinePhaseLifecycleStage.PRE_EXECUTE_REPO  || true
| DocumentType.TIR         | PROJECT_GAMP_5 | REPO_ODS_CODE    | PipelinePhases.DEPLOY   | PipelinePhaseLifecycleStage.POST_EXECUTE_REPO || true
| DocumentType.TIR         | PROJECT_GAMP_5 | REPO_ODS_SERVICE | PipelinePhases.DEPLOY   | PipelinePhaseLifecycleStage.POST_EXECUTE_REPO || true
```

**Review by clemensutschig — APPROVED** [review]

**Comment by metmajer** [comment]
FYI @georgfedermann

**Pull request merged**
