### PR TITLE
enable log output when testing

### PR DESCRIPTION
**Pull request by oalyman**
Log output when testing was not working, so I enabled it.
Therefore I needed to change the test directory layout and aligned it to the default groovy gradle layout

now it is:
```
test/groovy    -> for groovy files
test/resources -> for test resources that should be in the classpath
```

besides that:
- upgrade gradle-wrapper to most recent version
- align `@Grab` and `build.gradle` dependency version (unirest-java)
- use classpath based resolution of resources

### CODE REVIEW

**Review by clemensutschig — COMMENTED** [review]
love it .. but @metmajer should review .. because its a major change ... :)

**Comment by metmajer** [comment]
@oalyman can you provide your change on a publicly available feature branch? I need to run this in a pipeline before I can give my LGTM. Cheers!

**Comment by oalyman** [comment]
> @oalyman can you provide your change on a publicly available feature branch? I need to run this in a pipeline before I can give my LGTM. Cheers!

@metmajer Doesn't this one work for you?
https://github.com/BIX-Digital/ods-mro-jenkins-shared-library/tree/feature/enable-logging-in-tests

**Comment by metmajer** [comment]
@oalyman busy getting a couple of changes done. Will resolve in the next days!

**Comment by metmajer** [comment]
@oalyman can you please merge/rebase from master?

**Pull request closed without merging**
