### PR TITLE
Refactor LeVA docs and production environment support

### LINKED ISSUE #74: Refactor to support LeVA document data via a central REST endpoint
Currently, the release manager collects data needed for LeVA document generation from various Jira REST endoints. This has posed technical limitations and increased the complexity of our implementation.

As a solution, our integration with Jira will use a custom-developed REST endpoint to deliver data in a conveniently navigable structure.

We need to refactor our implementation to accommodate the custom REST endpoint and remove code that is not needed anymore.

### PR DESCRIPTION
**Pull request by metmajer**
This PR radically removes code not needed anymore and introduces a class `Project` that provides convenient access to all project-related data:

- build params
- project metadata (`metadata.yml`)
- repository metadata (`metadata.yml`) and release manager settings (`release-manager.yml`)
- Jira data provided by the custom REST endpoint (currently uses fake data)

Closes #74

### CODE REVIEW

**Comment by metmajer** [comment]
@clemensutschig @hrcornejo approve, but don't merge!

@oalyman @georgfedermann FYI

**Comment by michaelsauter** [comment]
@metmajer @hrcornejo Please do not make any further changes to `phaseInit` and `Project` interaction. This was said to be "stable" but now I have to re-apply our changes to the new situation (different loading order, invocation, etc.) ... this really hurts us. Please give us a shout if you have to make changes so we can understand and adjust.

**Comment by metmajer** [comment]
@michaelsauter the Project has been work in progress, we only considered the jobs in /vars stable. Because of new structures in the Jira project, which has only stabilized yesterday, there is another feature branch at feature/adapt-new-project-structures that will add extra interactions to backfill shortcomings that could not be implemented by other teams in Jira. We cannot change this.

Other than merge conflicts, what is bothering you?

**Comment by michaelsauter** [comment]
@metmajer I would have preferred to see @oalyman and my work in their original commit, rather to have it mixed with lots of other work. Can we please avoid this in the future?

Also - as I said yesterday - this branch is effectively master, so what is holding us back from merging it? I don't see value holding on to this branch any longer ...

**Comment by metmajer** [comment]
@michaelsauter @oalyman usually, feature branches get reduced to a single commit to avoid cluttering the Git history. This branch, however, will be merged with all commits contained (as-is). Before we merge into master, your contribution will be attributed solely to you both by using a `git rebase`.

The reason this branch is not yet merged with master is that it is still work in progress. We have not yet managed to run a pipeline end-to-end. You'll understand that this is a pre-requisite to not taint master.

**Pull request merged**
